Add feature for Alert
AirenSoft/OvenMediaEngine pull request #1204
Opened 2023-04-27 07:35 UTC by choigilhoon

The purpose of this P.R. is to add a module that can detect anomalies and interesting patterns in a stream or system, and send notifications to the user.

Detailed information has been written at https://airensoft.gitbook.io/ovenmediaengine/v/master-1/alert.

2023-04-28 17:00 UTC, getroot requested changes

2023-04-28 17:00 UTC, getroot commented on src/projects/monitoring/alert/alert.cpp
> +      if (alert.IsParsed() == false || rules.IsParsed() == false)
It is better to check this in Alert::Start and return false.

2023-04-28 17:00 UTC, getroot commented on src/projects/monitoring/alert/alert.h
> +      bool NeedsAlert(const ov::String &source_uri, const std::shared_ptr<std::vector<std::shared_ptr<Message>>> &message_list);
I think `IsAlertNeeded` is better naming

2023-04-28 17:00 UTC, getroot commented on src/projects/monitoring/alert/alert.h
> +      void ValidateIngressRules(const ov::String &source_uri, cfg::alrt::rule::Rules rules, const std::shared_ptr<StreamMetrics> &stream_metric, const std::shared_ptr<std::vector<std::shared_ptr<Mess
"`verify`" seems more appropriate in this situation than "`validate`".

2023-05-08 07:37 UTC, dimiden commented on src/projects/monitoring/alert/alert.cpp
Indentation must be done using tabs

2023-05-08 07:37 UTC, dimiden commented on src/projects/monitoring/alert/notification.cpp
There is inconsistency in the indentation

2023-05-08 07:37 UTC, dimiden commented on src/projects/monitoring/alert/notification.cpp
> +		void Notification::ParseResponse(const std::shared_ptr<ov::Data> &data)
Please use ```const``` when the data is not being modified

2023-05-08 07:37 UTC, dimiden commented on src/projects/monitoring/alert/notification.h
> +			ov::String GetErrReason() const;
Since ```error``` is not a long word, it is recommended to avoid using abbreviations

2023-05-08 07:37 UTC, dimiden commented on src/projects/monitoring/alert/notification.cpp
> +				SetStatus(StatusCode::INTERNAL_ERROR, ov::String::FormatString("Signature creation failed.(Method : HMAC(SHA1), Key : %s, Body length : %d", _secret_key.CStr(), body.GetLength()));
```GetErrReason()``` is a "public" API, and there is a concern that unintended usage might expose the key value to the external system. Please adjust the access level or modify it to ensure that the key value is not exposed

2023-05-08 07:37 UTC, dimiden commented on src/projects/monitoring/alert/notification.h
> +			uint64_t _timeout_msec = 0;
Please ensure consistency in the suffix of variable names, either using ```msec``` or ```ms``` throughout.

2023-05-08 07:37 UTC, dimiden commented on src/projects/config/items/alert/rules/ingress/ingress.h
> +				CFG_DECLARE_CONST_REF_GETTER_OF(GetHasBFrame, _has_b_frame)
For consistency, please change it to ```HasBframes``` (referring to ```VideoTrack::HasBframes```)

2023-05-08 07:37 UTC, dimiden commented on src/projects/monitoring/alert/alert.cpp
> +          for (const auto& [stream_key, stream_metric] : app_metric->GetStreamMetricsMap())
Please align the code format for ```&``` by using the ```const auto &[``` style instead of ```const auto&[```

2023-05-09 03:43 UTC, getroot approved these changes

2023-05-15 06:20 UTC, choigilhoon commented
@dimiden 
Modified the format to be consistent with the same indentation.

2023-05-15 06:47 UTC, dimiden approved these changes

2023-05-15 06:48 UTC, merged